### ISSUE TITLE
Bilibili，直播小工具失效，请作者尽快修复。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#10]
直播小工具V2.7.7，进入B站UP主的直播间，跳出"html注入成功！享用脚本"与wss服务器连接成功”提示以后，点击鼠标右键，二级菜单没有像往常那样，出现“小工具”和录制直播流等选项，也没有出现”直播切片“等选项，感觉在B站的直播间，这个油猴脚本失效了，请作者尽快修复。

![直播小工具失效截图1](https://user-images.githubusercontent.com/103800975/183639062-eea63ee9-123a-464e-ae20-a95873adf36f.jpg)

PS：现在，我在油猴插件里，只安装和开启了这1个插件，所以完全不存在这个脚本和其他插件互相冲突的问题。

![直播小工具失效截图2](https://user-images.githubusercontent.com/103800975/183639740-88b31d27-bd3b-46fd-9b0f-86f9a2b644d3.jpg)

**Comment by isma123HH** [comment]
提供一下控制台报错

**Comment by Yukihana-Lamy** [comment]
> 提供一下控制台报错

F12控制台报错截图

![B站小工具失效截图1](https://user-images.githubusercontent.com/103800975/184578586-78b61db3-7d5c-4471-b6f0-9817ea08a686.jpg)

![B站小工具失效截图2](https://user-images.githubusercontent.com/103800975/184578600-dc1500c5-ce89-4aee-8e25-94ea5156a6ee.jpg)

![B站小工具失效截图3](https://user-images.githubusercontent.com/103800975/184578622-cd49fb48-81ec-421d-a7f2-e1859421f9ac.jpg)

![B站小工具失效截图4](https://user-images.githubusercontent.com/103800975/184578682-0b54e3fe-dc01-4185-a949-1f779757bcd9.jpg)

![B站小工具失效截图5](https://user-images.githubusercontent.com/103800975/184578706-c7437a16-29e8-4333-8016-0cce73a825d1.jpg)



希望B站直播小工具的作者尽快修复这些BUG.........

**Comment by Yukihana-Lamy** [comment]
![Uploading B站小工具失效截图6.jpg…]()

**Comment by Yukihana-Lamy** [comment]
> 提供一下控制台报错

![B站小工具失效截图6](https://user-images.githubusercontent.com/103800975/184578865-64a9d6a7-6526-43ca-bf81-f3fee015dcbe.jpg)

**Comment by isma123HH** [comment]
> > 提供一下控制台报错
> 
> ![B站小工具失效截图6](https://user-images.githubusercontent.com/103800975/184578865-64a9d6a7-6526-43ca-bf81-f3fee015dcbe.jpg)

我推测是在获取主播uid等等信息时出错了，使用这个版本看看有没有报错
https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/zhuobo_info_fix/bili_live_assistant.user.js

**Comment by Yukihana-Lamy** [comment]
> > > 提供一下控制台报错
> > 
> > 
> > ![B站小工具失效截图6](https://user-images.githubusercontent.com/103800975/184578865-64a9d6a7-6526-43ca-bf81-f3fee015dcbe.jpg)
> 
> 我推测是在获取主播uid等等信息时出错了，使用这个版本看看有没有报错 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/zhuobo_info_fix/bili_live_assistant.user.js

我今天上午测试过了，作者你给我的这个链接，这个版本的直播小工具在B站直播间观看直播的时候，二级菜单各项功能可以正常显示，是有效的。

**Comment by isma123HH** [comment]
> 

好的
