### ISSUE TITLE
画质

### ISSUE THREAD

**Issue by npcXxX** [isma123HH/bilibili_live-assistant#15]
直播流画质分辨率只有720p 不是按照直播间选择的分辨率生成的
这是链接参数 /live_7734200_bs_7236416_1500.flv

**Comment by npcXxX** [comment]
可以参考一下这个js 可能的话可以把其他直播流获取也加一下
https://www.52pojie.cn/thread-1555714-1-1.html

**Comment by isma123HH** [comment]
代码编写之初为了方便只获取了最低分辨率的流，以后会先检测当前直播间的流分辨率再去获取。

**Comment by isma123HH** [comment]
你好，2.8.2版本已在近期更新，现在获取直播流时可以选择分辨率了。
