### ISSUE TITLE
作者，这直播切片复制的直播流链接，直播流播放器同样无法播放。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#2]
作者，这直播切片复制的直播流链接，直播流播放器同样无法播放。

**Comment by isma123HH** [comment]
请您提供一下出现问题的房间号。

**Comment by Yukihana-Lamy** [comment]
5948992

**Comment by Yukihana-Lamy** [comment]
我测试的直播房间，直播切片复制的直播流链接，直播流播放器都无法播放。而且我将直播切片复制的链接粘贴到了本地播放器，同样无法播放。

**Comment by isma123HH** [comment]
有些直播间并不支持直播切片，这个直播间可能就是不支持的其中之一。
复制出来的直播切片链接是否是 "null 或 undefined &tmshift=xxx" ？如果是的话就证明不支持该房间，近期我会根据你的问题发布一个新版本，请您使用新版本查看问题是否解决。

**Comment by Yukihana-Lamy** [comment]
> 有些直播间并不支持直播切片，这个直播间可能就是不支持的其中之一。 复制出来的直播切片链接是否是 "null 或 undefined &tmshift=xxx" ？如果是的话就证明不支持该房间，近期我会根据你的问题发布一个新版本，请您使用新版本查看问题是否解决。

是的。就是这样的链接。

**Comment by Yukihana-Lamy** [comment]
> 有些直播间并不支持直播切片，这个直播间可能就是不支持的其中之一。 复制出来的直播切片链接是否是 "null 或 undefined &tmshift=xxx" ？如果是的话就证明不支持该房间，近期我会根据你的问题发布一个新版本，请您使用新版本查看问题是否解决。

就算不是这样的链接，复制出来以后，直播流播放器同样无法播放。

打开F12以后，错误信息截图

![B站直播小工具直播切片bug1](https://user-images.githubusercontent.com/103800975/171324721-0b96641d-87a7-4a14-bb1d-88208c9388d6.jpg)

**Comment by isma123HH** [comment]
> > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> 
> 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？

感谢您的回复，因为直播链接是null（空的），所以无法播放。
我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined）
以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。

**Comment by Yukihana-Lamy** [comment]
> > > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> > 
> > 
> > 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？
> 
> 感谢您的回复，因为直播链接是null（空的），所以无法播放。 我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined） 以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。

新版脚本复制的【直播切片】链接地址，直播流播放器也仍然是无法播放。

![B站直播小工具直播切片bug2](https://user-images.githubusercontent.com/103800975/171337451-3be6d70c-716d-451e-a14d-e8c0d71612c2.jpg)

**Comment by isma123HH** [comment]
> > > > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> > > 
> > > 
> > > 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？
> > 
> > 
> > 感谢您的回复，因为直播链接是null（空的），所以无法播放。 我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined） 以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。
> 
> 新版脚本复制的【直播切片】链接地址，直播流播放器也仍然是无法播放。
> 
> ![B站直播小工具直播切片bug2](https://user-images.githubusercontent.com/103800975/171337451-3be6d70c-716d-451e-a14d-e8c0d71612c2.jpg)

你这个问题非常奇怪，我自己测试了一下能播放
![QQ截图20220601140222](https://user-images.githubusercontent.com/102177279/171338105-b466f54e-ce3d-4067-be7d-fc9c0f8a0b6b.png)
https://cn-sdjn2-cmcc-live-02.bilivideo.com/live-bvc/889822/live_2099161_48639401_1500.m3u8?cdn=cn-gotcha01&expires=1654066975&len=0&oi=3083260996&pt=h5&qn=150&trid=1003e915051c940c499da119100dafaa96f8&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=137561272596c01a64e228c5c6cda659&ptype=0&src=57345&sl=1&source=one&sid=6618&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1
也许可能是因为引用的脚本没有加载上？https://cdn.jsdelivr.net/npm/xgplayer-hls.js@2.2.2/browser/index.js
另外我也换了一个浏览器尝试了一下，发现有的时候确实可能因为网络原因加载不上https://cdn.jsdelivr.net/ 的外部脚本。

**Comment by Yukihana-Lamy** [comment]
> > > > > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> > > > 
> > > > 
> > > > 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？
> > > 
> > > 
> > > 感谢您的回复，因为直播链接是null（空的），所以无法播放。 我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined） 以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。
> > 
> > 
> > 新版脚本复制的【直播切片】链接地址，直播流播放器也仍然是无法播放。
> > ![B站直播小工具直播切片bug2](https://user-images.githubusercontent.com/103800975/171337451-3be6d70c-716d-451e-a14d-e8c0d71612c2.jpg)
> 
> 你这个问题非常奇怪，我自己测试了一下能播放 ![QQ截图20220601140222](https://user-images.githubusercontent.com/102177279/171338105-b466f54e-ce3d-4067-be7d-fc9c0f8a0b6b.png) https://cn-sdjn2-cmcc-live-02.bilivideo.com/live-bvc/889822/live_2099161_48639401_1500.m3u8?cdn=cn-gotcha01&expires=1654066975&len=0&oi=3083260996&pt=h5&qn=150&trid=1003e915051c940c499da119100dafaa96f8&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=137561272596c01a64e228c5c6cda659&ptype=0&src=57345&sl=1&source=one&sid=6618&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1 也许可能是因为引用的脚本没有加载上？https://cdn.jsdelivr.net/npm/xgplayer-hls.js@2.2.2/browser/index.js 另外我也换了一个浏览器尝试了一下，发现有的时候确实可能因为网络原因加载不上https://cdn.jsdelivr.net/ 的外部脚本。

感觉在直播流播放器里粘贴【直播切片】的直播流链接，没任何反应，也看不了直播回放。

**Comment by isma123HH** [comment]
> > > > > > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> > > > > 
> > > > > 
> > > > > 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？
> > > > 
> > > > 
> > > > 感谢您的回复，因为直播链接是null（空的），所以无法播放。 我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined） 以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。
> > > 
> > > 
> > > 新版脚本复制的【直播切片】链接地址，直播流播放器也仍然是无法播放。
> > > ![B站直播小工具直播切片bug2](https://user-images.githubusercontent.com/103800975/171337451-3be6d70c-716d-451e-a14d-e8c0d71612c2.jpg)
> > 
> > 
> > 你这个问题非常奇怪，我自己测试了一下能播放 ![QQ截图20220601140222](https://user-images.githubusercontent.com/102177279/171338105-b466f54e-ce3d-4067-be7d-fc9c0f8a0b6b.png) https://cn-sdjn2-cmcc-live-02.bilivideo.com/live-bvc/889822/live_2099161_48639401_1500.m3u8?cdn=cn-gotcha01&expires=1654066975&len=0&oi=3083260996&pt=h5&qn=150&trid=1003e915051c940c499da119100dafaa96f8&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=137561272596c01a64e228c5c6cda659&ptype=0&src=57345&sl=1&source=one&sid=6618&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1 也许可能是因为引用的脚本没有加载上？https://cdn.jsdelivr.net/npm/xgplayer-hls.js@2.2.2/browser/index.js 另外我也换了一个浏览器尝试了一下，发现有的时候确实可能因为网络原因加载不上https://cdn.jsdelivr.net/ 的外部脚本。
> 
> 感觉在直播流播放器里粘贴【直播切片】的直播流链接，没任何反应，也看不了直播回放。

如果播放器连黑屏加载都没有，请使用这个脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/change_cdn/bili_live_assistant.user.js 我更换了外部脚本的cdn。

**Comment by Yukihana-Lamy** [comment]
> > > > > > > 复制出来的直播片段链接是否是“null 或 undefined &tmshift=xxx”？如果是的话就证明不支持这个房间，近期我会根据您的问题发布一个新版本，请您使用新版本查看问题是否解决。
> > > > > > 
> > > > > > 
> > > > > > 我还可以解释一下，为什么【直播片断】复制出来的链接，本地播放器无法播放，“找不到文件”？
> > > > > 
> > > > > 
> > > > > 感谢您的回复，因为直播链接是null（空的），所以无法播放。 我这边上传一个调试中的脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/bili_live_assistant.user.js ，您导入到油猴试一下直播切片复制的链接是否正常？（没有null或undefined） 以及，如果新版脚本复制的链接本地播放器也无法播放，请您附带上复制的直播链接并反馈。
> > > > 
> > > > 
> > > > 新版脚本复制的【直播切片】链接地址，直播流播放器也仍然是无法播放。
> > > > ![B站直播小工具直播切片bug2](https://user-images.githubusercontent.com/103800975/171337451-3be6d70c-716d-451e-a14d-e8c0d71612c2.jpg)
> > > 
> > > 
> > > 你这个问题非常奇怪，我自己测试了一下能播放 ![QQ截图20220601140222](https://user-images.githubusercontent.com/102177279/171338105-b466f54e-ce3d-4067-be7d-fc9c0f8a0b6b.png) https://cn-sdjn2-cmcc-live-02.bilivideo.com/live-bvc/889822/live_2099161_48639401_1500.m3u8?cdn=cn-gotcha01&expires=1654066975&len=0&oi=3083260996&pt=h5&qn=150&trid=1003e915051c940c499da119100dafaa96f8&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=137561272596c01a64e228c5c6cda659&ptype=0&src=57345&sl=1&source=one&sid=6618&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1 也许可能是因为引用的脚本没有加载上？https://cdn.jsdelivr.net/npm/xgplayer-hls.js@2.2.2/browser/index.js 另外我也换了一个浏览器尝试了一下，发现有的时候确实可能因为网络原因加载不上https://cdn.jsdelivr.net/ 的外部脚本。
> > 
> > 
> > 感觉在直播流播放器里粘贴【直播切片】的直播流链接，没任何反应，也看不了直播回放。
> 
> 如果播放器连黑屏加载都没有，请使用这个脚本 https://github.com/isma123HH/bilibili_live-assistant/raw/main/debug/change_cdn/bili_live_assistant.user.js 我更换了外部脚本的cdn。

感觉作者的这个B站直播小工具，与以下这个脚本有冲突，会导致【直播切片】里复制和粘贴到直播流播放器的直播地址链接，无法播放。

![B站直播小工具冲突脚本](https://user-images.githubusercontent.com/103800975/171804659-3dc79ee9-5ef6-4296-86e3-83d602e8fff1.jpg)

**Comment by isma123HH** [comment]
> 感觉作者的这个B站直播小工具，与以下这个脚本有冲突，会导致【直播切片】里复制和粘贴到直播流播放器的直播地址链接，无法播放。
> 
> ![B站直播小工具冲突脚本](https://user-images.githubusercontent.com/103800975/171804659-3dc79ee9-5ef6-4296-86e3-83d602e8fff1.jpg)

感谢您提供的反馈，经过核实，这两个脚本一起用的确会导致错误。我们会尝试修复的

**Comment by Yukihana-Lamy** [comment]
> > 感觉作者的这个B站直播小工具，与以下这个脚本有冲突，会导致【直播切片】里复制和粘贴到直播流播放器的直播地址链接，无法播放。
> > ![B站直播小工具冲突脚本](https://user-images.githubusercontent.com/103800975/171804659-3dc79ee9-5ef6-4296-86e3-83d602e8fff1.jpg)
> 
> 感谢您提供的反馈，经过核实，这两个脚本一起用的确会导致错误。我们会尝试修复的

还有1个脚本，和B站直播小工具脚本一起启用，同样会导致【直播切片】里复制和粘贴到直播流播放器的直播地址链接，还有复制和粘贴到直播流播放器的M3U8地址链接无法播放。

![B站直播小工具冲突脚本2](https://user-images.githubusercontent.com/103800975/171821234-312532d5-e687-4816-b527-af9bbaadd833.jpg)

**Comment by isma123HH** [comment]
> 还有1个脚本，和B站直播小工具脚本一起启用，同样会导致【直播切片】里复制和粘贴到直播流播放器的直播地址链接，还有复制和粘贴到直播流播放器的M3U8地址链接无法播放。
> 
> ![B站直播小工具冲突脚本2](https://user-images.githubusercontent.com/103800975/171821234-312532d5-e687-4816-b527-af9bbaadd833.jpg)

感谢你提出的反馈，但很抱歉，至少现在我无法修复这两个问题。
我推荐只启用本脚本来获得最佳体验，和其他脚本混合使用可能会导致意想不到的错误。
