### ISSUE TITLE
现在进入B站直播间，还经常会出现点击右键没反应的问题。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#3]
现在进入B站直播间，还经常会出现点击右键没反应的问题。请问作者，这正常嘛？

**Comment by isma123HH** [comment]
弹出过加载成功的提示吗？
![QQ截图20220601162958](https://user-images.githubusercontent.com/102177279/171362144-cc0ccb7f-79b5-44ec-8385-e6006da8f47e.png)
如果没有，那很有可能是因为脚本正在加载外部js。

**Comment by Yukihana-Lamy** [comment]
> 弹出过加载成功的提示吗？ ![QQ截图20220601162958](https://user-images.githubusercontent.com/102177279/171362144-cc0ccb7f-79b5-44ec-8385-e6006da8f47e.png) 如果没有，那很有可能是因为脚本正在加载外部js。

弹出过"html注入成功！享用脚本“的提示、还有”与wss服务器连接成功“的提示，但是我点击右键，就是什么反应都没有，没有弹出菜单栏。。。

**Comment by isma123HH** [comment]
> 

刷新几次一般就可以了

**Comment by Yukihana-Lamy** [comment]
> > 
> 
> 刷新几次一般就可以了

我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。

**Comment by isma123HH** [comment]
> > > 
> > 
> > 
> > 刷新几次一般就可以了
> 
> 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。

F12控制台截图看看

**Comment by Yukihana-Lamy** [comment]
> > > > 
> > > 
> > > 
> > > 刷新几次一般就可以了
> > 
> > 
> > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> 
> F12控制台截图看看

F12控制台截图信息

![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)

**Comment by isma123HH** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 刷新几次一般就可以了
> > > 
> > > 
> > > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> > 
> > 
> > F12控制台截图看看
> 
> F12控制台截图信息
> 
> ![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)

请将右上角搜索框的"m3u8"清除掉再打开F12截图报错（要完整，一张截不下就多截几张）

**Comment by Yukihana-Lamy** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 刷新几次一般就可以了
> > > > 
> > > > 
> > > > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> > > 
> > > 
> > > F12控制台截图看看
> > 
> > 
> > F12控制台截图信息
> > ![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)
> 
> 请将右上角搜索框的"m3u8"清除掉再打开F12截图报错（要完整，一张截不下就多截几张）

打开F12以后的报错信息

![B站直播间小工具F12错误1](https://user-images.githubusercontent.com/103800975/171390233-703c9ec6-01b2-4c73-b605-545a029995dc.jpg)

![B站直播间小工具F12错误2](https://user-images.githubusercontent.com/103800975/171390271-bd6cde44-435a-47c1-bd0b-7b2a2413f137.jpg)

![B站直播间小工具F12错误3](https://user-images.githubusercontent.com/103800975/171390304-c271cc06-67f5-4987-8e55-e88f2cbadd14.jpg)

![B站直播间小工具F12错误4](https://user-images.githubusercontent.com/103800975/171390350-3d0d24fc-29d9-4925-867c-be255e79d58d.jpg)

![B站直播间小工具F12错误5](https://user-images.githubusercontent.com/103800975/171390413-eac3be25-22f6-4c98-a422-00c19fc4a5e9.jpg)

![B站直播间小工具F12错误6](https://user-images.githubusercontent.com/103800975/171390446-a948d800-6ec2-40d5-9fb8-a0ff78403298.jpg)

![B站直播间小工具F12错误7](https://user-images.githubusercontent.com/103800975/171390475-54cc587f-d8a1-4587-a78e-3dea749afe73.jpg)

**Comment by isma123HH** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 刷新几次一般就可以了
> > > > > 
> > > > > 
> > > > > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> > > > 
> > > > 
> > > > F12控制台截图看看
> > > 
> > > 
> > > F12控制台截图信息
> > > ![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)
> > 
> > 
> > 请将右上角搜索框的"m3u8"清除掉再打开F12截图报错（要完整，一张截不下就多截几张）
> 
> 打开F12以后的报错信息
> 
> ![B站直播间小工具F12错误1](https://user-images.githubusercontent.com/103800975/171390233-703c9ec6-01b2-4c73-b605-545a029995dc.jpg)
> 
> ![B站直播间小工具F12错误2](https://user-images.githubusercontent.com/103800975/171390271-bd6cde44-435a-47c1-bd0b-7b2a2413f137.jpg)
> 
> ![B站直播间小工具F12错误3](https://user-images.githubusercontent.com/103800975/171390304-c271cc06-67f5-4987-8e55-e88f2cbadd14.jpg)
> 
> ![B站直播间小工具F12错误4](https://user-images.githubusercontent.com/103800975/171390350-3d0d24fc-29d9-4925-867c-be255e79d58d.jpg)
> 
> ![B站直播间小工具F12错误5](https://user-images.githubusercontent.com/103800975/171390413-eac3be25-22f6-4c98-a422-00c19fc4a5e9.jpg)
> 
> ![B站直播间小工具F12错误6](https://user-images.githubusercontent.com/103800975/171390446-a948d800-6ec2-40d5-9fb8-a0ff78403298.jpg)
> 
> ![B站直播间小工具F12错误7](https://user-images.githubusercontent.com/103800975/171390475-54cc587f-d8a1-4587-a78e-3dea749afe73.jpg)

控制台右上角的“仅限信息”过滤掉了报错，勾选全部选项后再刷新截图。另外建议你只启用本脚本然后截图报错内容，方便我找到出现错误的代码位置。

**Comment by Yukihana-Lamy** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 刷新几次一般就可以了
> > > > > > 
> > > > > > 
> > > > > > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> > > > > 
> > > > > 
> > > > > F12控制台截图看看
> > > > 
> > > > 
> > > > F12控制台截图信息
> > > > ![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)
> > > 
> > > 
> > > 请将右上角搜索框的"m3u8"清除掉再打开F12截图报错（要完整，一张截不下就多截几张）
> > 
> > 
> > 打开F12以后的报错信息
> > ![B站直播间小工具F12错误1](https://user-images.githubusercontent.com/103800975/171390233-703c9ec6-01b2-4c73-b605-545a029995dc.jpg)
> > ![B站直播间小工具F12错误2](https://user-images.githubusercontent.com/103800975/171390271-bd6cde44-435a-47c1-bd0b-7b2a2413f137.jpg)
> > ![B站直播间小工具F12错误3](https://user-images.githubusercontent.com/103800975/171390304-c271cc06-67f5-4987-8e55-e88f2cbadd14.jpg)
> > ![B站直播间小工具F12错误4](https://user-images.githubusercontent.com/103800975/171390350-3d0d24fc-29d9-4925-867c-be255e79d58d.jpg)
> > ![B站直播间小工具F12错误5](https://user-images.githubusercontent.com/103800975/171390413-eac3be25-22f6-4c98-a422-00c19fc4a5e9.jpg)
> > ![B站直播间小工具F12错误6](https://user-images.githubusercontent.com/103800975/171390446-a948d800-6ec2-40d5-9fb8-a0ff78403298.jpg)
> > ![B站直播间小工具F12错误7](https://user-images.githubusercontent.com/103800975/171390475-54cc587f-d8a1-4587-a78e-3dea749afe73.jpg)
> 
> 控制台右上角的“仅限信息”过滤掉了报错，勾选全部选项后再刷新截图。另外建议你只启用本脚本然后截图报错内容，方便我找到出现错误的代码位置。

除了【B站直播小工具】，我将油猴里的其他脚本全部关掉了。现在，点击右键有反应了。我认为，应该是某些插件和这个脚本冲突了，导致这个脚本出现提示以后，我点击右键没有任何反应。

**Comment by isma123HH** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 刷新几次一般就可以了
> > > > > > > 
> > > > > > > 
> > > > > > > 我刷新了5~6次，还是这样，点击右键，任何反应都没有，也没有弹出菜单栏。
> > > > > > 
> > > > > > 
> > > > > > F12控制台截图看看
> > > > > 
> > > > > 
> > > > > F12控制台截图信息
> > > > > ![B站直播小工具未弹出菜单1](https://user-images.githubusercontent.com/103800975/171385624-b384adec-74fa-412a-81bc-d310c656c33b.jpg)
> > > > 
> > > > 
> > > > 请将右上角搜索框的"m3u8"清除掉再打开F12截图报错（要完整，一张截不下就多截几张）
> > > 
> > > 
> > > 打开F12以后的报错信息
> > > ![B站直播间小工具F12错误1](https://user-images.githubusercontent.com/103800975/171390233-703c9ec6-01b2-4c73-b605-545a029995dc.jpg)
> > > ![B站直播间小工具F12错误2](https://user-images.githubusercontent.com/103800975/171390271-bd6cde44-435a-47c1-bd0b-7b2a2413f137.jpg)
> > > ![B站直播间小工具F12错误3](https://user-images.githubusercontent.com/103800975/171390304-c271cc06-67f5-4987-8e55-e88f2cbadd14.jpg)
> > > ![B站直播间小工具F12错误4](https://user-images.githubusercontent.com/103800975/171390350-3d0d24fc-29d9-4925-867c-be255e79d58d.jpg)
> > > ![B站直播间小工具F12错误5](https://user-images.githubusercontent.com/103800975/171390413-eac3be25-22f6-4c98-a422-00c19fc4a5e9.jpg)
> > > ![B站直播间小工具F12错误6](https://user-images.githubusercontent.com/103800975/171390446-a948d800-6ec2-40d5-9fb8-a0ff78403298.jpg)
> > > ![B站直播间小工具F12错误7](https://user-images.githubusercontent.com/103800975/171390475-54cc587f-d8a1-4587-a78e-3dea749afe73.jpg)
> > 
> > 
> > 控制台右上角的“仅限信息”过滤掉了报错，勾选全部选项后再刷新截图。另外建议你只启用本脚本然后截图报错内容，方便我找到出现错误的代码位置。
> 
> 除了【B站直播小工具】，我将油猴里的其他脚本全部关掉了。现在，点击右键有反应了。我认为，应该是某些插件和这个脚本冲突了，导致这个脚本出现提示以后，我点击右键没有任何反应。

是的，我的想法也是这样。但您启用的脚本似乎多达36个，我并没有时间和您一一核对，还请您以后在使用过程中发现并反馈是和哪个脚本冲突了。
