### ISSUE TITLE
若是能让用户在观看直播的时候，自行选择清晰度就好了。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#4]
在使用【插件菜单】里的直播流播放器观看视频网站在线直播的时候，能让用户自行选择直播的清晰度就好了，不知道作者能做到嘛？

**Comment by isma123HH** [comment]
当然可以做到，我会在播放器里面尝试内置的。

**Comment by isma123HH** [comment]
已经更新该功能。

**Comment by Yukihana-Lamy** [comment]
> 已经更新该功能。

我就看到，进了直播间，右键，浏览器菜单栏里多了【添加进收藏夹】选项。直播流播放器的右下角MS多了【画中画】和【进入全屏】选项，还是无法选择清晰度。
