### ISSUE TITLE
感觉【插件菜单】里的直播流播放器过于简易了，希望作者添加保存直播视频和下载直播视频的功能。。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#5]
1.感觉【插件菜单】里的直播流播放器过于简易了，希望将各大视频网站的直播流地址复制和粘贴至直播流播放器里以后，在线观看各大视频网站的在线直播时，能添加可以将该直播视频保存和下载的功能，作者能做到这点吗？

2.若是能做到这点，希望作者另外再详细说明一下，如何使用本地视频播放器，播放M3U8格式的视频？

**Comment by isma123HH** [comment]
1.是可以实现的，但可能需要涉及到本地转码，所以这个功能可能会被暂时搁置一段时间。
2.下载<a href=http://potplayer.tv/>PotPlayer</a> （这个网站可能需要加速才能访问，如果不能正常访问请自行寻找一个信任的网站下载）后 右键播放器
![QQ截图20220603154253](https://user-images.githubusercontent.com/102177279/171810724-e91e2c1c-c50c-4382-99c0-c0eb7d79720d.png)  <br>打开->打开链接，然后在弹出框填入复制到的直播流链接，加载完毕后即可播放。

**Comment by Yukihana-Lamy** [comment]
> 1.是可以实现的，但可能需要涉及到本地转码，所以这个功能可能会被暂时搁置一段时间。 2.下载[PotPlayer](http://potplayer.tv/) （这个网站可能需要加速才能访问，如果不能正常访问请自行寻找一个信任的网站下载）后 右键播放器 ![QQ截图20220603154253](https://user-images.githubusercontent.com/102177279/171810724-e91e2c1c-c50c-4382-99c0-c0eb7d79720d.png) 打开->打开链接，然后在弹出框填入复制到的直播流链接，加载完毕后即可播放。

pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏，播放在线直播视频以后，如何收藏播放的在线直播视频？

**Comment by isma123HH** [comment]
> pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏进行播放以后，如何收藏播放的视频？

我不推荐收藏链接，因为如果你仔细研究一下，会发现每次获取的直播流链接都不一样。
https://cn-hnzz-cmcc-v-11.bilivideo.com/live-bvc/526772/live_194484313_8775758_1500.m3u8?cdn=cn-gotcha01&expires=1654260195&len=0&oi=3083260996&pt=h5&qn=150&trid=100369acd83a1961486c9ab3dc88070ebb3b&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=0e071af4ba3bee3796a02dfbb2f20b3d&ptype=0&src=57345&sl=4&source=one&sid=5365&sk=7183dd5b59b454499a831dc80e8cd046&order=1 
<br>
https://cn-sxty2-cmcc-live-01.bilivideo.com/live-bvc/916114/live_194484313_8775758_1500.m3u8?cdn=cn-gotcha01&expires=1654260216&len=0&oi=3083260996&pt=h5&qn=150&trid=1003bb6b375ecfe241cea074882ceab5fe15&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=5cefee680762b4d76a1821b3aab4fcfc&ptype=0&src=57345&sl=4&source=one&sid=6510&sk=7183dd5b59b454499a831dc80e8cd046&order=1
可以看到这两个示例链接的host( cn-sxty2-cmcc-live-01.bilivideo.com 和 cn-hnzz-cmcc-v-11.bilivideo.com )并不一致。
并且主播每次开播后都会使"live_194484313_8775758_1500.m3u8"更改。
如果您有录播的需求，可以去看看<a href=https://github.com/BililiveRecorder/BililiveRecorder>这个软件 </a> 官网https://rec.danmuji.org/

**Comment by isma123HH** [comment]
> pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏进行播放以后，如何收藏播放的视频？

如果您真的很想使用收藏，可以参考下面的两张图
![QQ截图20220603195301](https://user-images.githubusercontent.com/102177279/171848528-ed5c3356-2797-4711-8ddc-e771e678aa89.png)
![QQ截图20220603195310](https://user-images.githubusercontent.com/102177279/171848570-81b6a776-bf0b-4d22-b565-fd1e4d4f392e.png)
点击添加链接后会弹出一个新窗口，相信不用我说您也会继续操作了。

**Comment by Yukihana-Lamy** [comment]
> > pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏进行播放以后，如何收藏播放的视频？
> 
> 如果您真的很想使用收藏，可以参考下面的两张图 ![QQ截图20220603195301](https://user-images.githubusercontent.com/102177279/171848528-ed5c3356-2797-4711-8ddc-e771e678aa89.png) ![QQ截图20220603195310](https://user-images.githubusercontent.com/102177279/171848570-81b6a776-bf0b-4d22-b565-fd1e4d4f392e.png) 点击添加链接后会弹出一个新窗口，相信不用我说您也会继续操作了。

即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是很好的。

**Comment by Yukihana-Lamy** [comment]
> > pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏进行播放以后，如何收藏播放的视频？
> 
> 如果您真的很想使用收藏，可以参考下面的两张图 ![QQ截图20220603195301](https://user-images.githubusercontent.com/102177279/171848528-ed5c3356-2797-4711-8ddc-e771e678aa89.png) ![QQ截图20220603195310](https://user-images.githubusercontent.com/102177279/171848570-81b6a776-bf0b-4d22-b565-fd1e4d4f392e.png) 点击添加链接后会弹出一个新窗口，相信不用我说您也会继续操作了。

即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是可以很好丰富这个脚本的功能。

**Comment by Yukihana-Lamy** [comment]
> > pot player视频播放器我电脑上也有安装，但是右键里那个【收藏】选项，我暂时还不是很会使用，不知道将直播流地址链接复制和粘贴到URL栏进行播放以后，如何收藏播放的视频？
> 
> 如果您真的很想使用收藏，可以参考下面的两张图 ![QQ截图20220603195301](https://user-images.githubusercontent.com/102177279/171848528-ed5c3356-2797-4711-8ddc-e771e678aa89.png) ![QQ截图20220603195310](https://user-images.githubusercontent.com/102177279/171848570-81b6a776-bf0b-4d22-b565-fd1e4d4f392e.png) 点击添加链接后会弹出一个新窗口，相信不用我说您也会继续操作了。

即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是可以很好的丰富这个脚本的功能。

**Comment by isma123HH** [comment]
> 即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是可以很好的丰富这个脚本的功能。

好想法，我会考虑的

**Comment by Yukihana-Lamy** [comment]
> > 即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是可以很好的丰富这个脚本的功能。
> 
> 好想法，我会考虑的

作者更新了这个脚本的版本，我在B站直播间点击右键，在【小功能】栏里看到了【录制直播】选项。就是录制B站直播的时候，看不见录制的时长和其他表示正在录制直播的标识，只是【小功能】栏里的【录制直播】选项成了【停止录制】选项。希望以后【录制直播】选项也能支持其他视频网站。

**Comment by Yukihana-Lamy** [comment]
> > 即使作者最终无法做到添加这2个功能，那若是可以给这个B站直播小工具添加直播录屏功能，也是可以很好的丰富这个脚本的功能。
> 
> 好想法，我会考虑的

还有，我想询问作者，这使用【小工具】里的【录制直播】选项录制的直播，录制完成以后会保存在电脑的哪里？也就是保存在电脑的哪个文件夹？

**Comment by isma123HH** [comment]
> 作者更新了这个脚本的版本，我在B站直播间点击右键，在【小功能】栏里看到了【录制直播】选项。就是录制B站直播的时候，看不见录制的时长和其他表示正在录制直播的标识，只是【小功能】栏里的【录制直播】选项成了【停止录制】选项。希望以后【录制直播】选项也能支持其他视频网站。

录制时长和录制标识是一个好想法，您建议将录制时长和录制标识放在哪里呢？
其他网站的录制直播后续会支持，但最近可能会专注哔哩哔哩的其他功能。

**Comment by isma123HH** [comment]
> 还有，我想询问作者，这使用【小工具】里的【录制直播】选项录制的直播，录制完成以后会保存在电脑的哪里？也就是保存在电脑的哪个文件夹？

在点击停止录制后会弹出提示并会在1.5秒后跳转到一个新页面，可以在新页面右键保存，或者播放器也有选项支持下载。
需要注意的是录制和保存的格式为webm

**Comment by Yukihana-Lamy** [comment]
> > 作者更新了这个脚本的版本，我在B站直播间点击右键，在【小功能】栏里看到了【录制直播】选项。就是录制B站直播的时候，看不见录制的时长和其他表示正在录制直播的标识，只是【小功能】栏里的【录制直播】选项成了【停止录制】选项。希望以后【录制直播】选项也能支持其他视频网站。
> 
> 录制时长和录制标识是一个好想法，您建议将录制时长和录制标识放在哪里呢？ 其他网站的录制直播后续会支持，但最近可能会专注哔哩哔哩的其他功能。

最好放在容易引起注意的位置，这样才能让这个脚本的用户注意得到。
