### ISSUE TITLE
抖音平台的直播，该脚本无法使用。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#6]
抖音平台的直播，在出现“html注入成功，享用脚本”提示以后，并没有出现“wss连接成功”的提示，点击右键也没出现和B站一样的、‘获取直播流”的菜单。右上角也没出现“插件菜单”选项。希望作者好好检查一下脚本，尽快修复这个问题。

**Comment by isma123HH** [comment]
抖音的使用方式和其他网站是有些不同的。
首先，脚本还暂不支持抖音直播间的wss链接。插件菜单这个功能我还没有想好加在哪里。以及抖音的网页播放器是不允许右键操作的。
关于直播流获取，这个功能暂时是做在了“手机观看”旁边的...里面
![QQ截图20220603154740](https://user-images.githubusercontent.com/102177279/171811554-de6de7cc-34b9-4817-823f-bab728506a8c.png)
暂时请参考本图使用，但未来可能有改动。
