### ISSUE TITLE
今天，发现本地视频播放器无法播放直播流地址链接了。。。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [isma123HH/bilibili_live-assistant#8]
今天，将【小功能】里的直播流地址链接复制和粘贴到本地视频播放器，无法播放了。只有直播流播放器还可以正常播放那些复制的直播流地址链接。。。

PS：我只打开了这1个油猴脚本，应该不会存在脚本冲突的问题。

![B站小工具bug1](https://user-images.githubusercontent.com/103800975/172524644-508cf565-8481-4a43-8066-148cc74a2d94.jpg)

![B站小工具bug2](https://user-images.githubusercontent.com/103800975/172524678-95c29dfe-0658-4e8b-8d46-695638473726.jpg)

**Comment by isma123HH** [comment]
> 今天，将【小功能】里的直播流地址链接复制和粘贴到本地视频播放器，无法播放了。只有直播流播放器还可以正常播放那些复制的直播流地址链接。。。
> 
> PS：我只打开了这1个油猴脚本，应该不会存在脚本冲突的问题。
> 
> ![B站小工具bug1](https://user-images.githubusercontent.com/103800975/172524644-508cf565-8481-4a43-8066-148cc74a2d94.jpg)
> 
> ![B站小工具bug2](https://user-images.githubusercontent.com/103800975/172524678-95c29dfe-0658-4e8b-8d46-695638473726.jpg)

感谢您的反馈。
经过我的调查，本地播放器是无法播放m3u8直播流的，**如果您有本地浏览的需求，可以使用获取"flv直播流"**。
